# Generated by Django 3.1.6 on 2021-03-17 21:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210317_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
