# Generated by Django 3.1.6 on 2021-03-23 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210317_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
