# Generated by Django 3.1.6 on 2021-03-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_cat',
            field=models.ForeignKey(blank=True, db_column='listing_cat', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category_choice', to_field='category'),
        ),
    ]
