# Generated by Django 3.1.6 on 2021-04-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='winner',
            new_name='win',
        ),
    ]
